apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ecommerce-storage
  hostPath:
    path: /data/ecommerce
