apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ecommerce-data
  namespace: ecommerce

spec:

  accessModes:
    - ReadWriteOnce

  storageClassName: ecommerce-ebs

  resources:
    requests:
      storage: 10Gi

